name: Pull request workflows

on:
  pull_request:
    branches: ["main"]
    types: ["opened", "synchronize"]
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  pytest:
    name: "Run python tests"
    runs-on: ubuntu-latest
    steps:
      - name: "📥 Fetching Repository Contents"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: "💫 Install package dependencies"
        run: |
          python -m pip install pytest
          python -m pip install -r requirements.txt

      - name: "🤖 Run pytest"
        run: |
          pytest test
